### ISSUE TITLE
Reading SMT-LIB causes Errors

### ISSUE THREAD

**Issue by lycurgus8** [pysmt/pysmt#692] opened 2021-04-29 08:40 UTC
Hi,
thanks for providing this library!
I recently started using pysmt and came across some question / potential bugs - as those are quite small topics I just put everything in a single issue:

- According to the readme interpolants can be computed with z3 but according to the change log (0.8.0) this does no longer work. Could you please clarify whether z3 can be used to compute interpolants or not?
- Can I somehow introduce "let" expressions -- like in SMT-LIB? I could not find anything regarding "let" in the API -- but as pysmt seems to use "let" for writing a SMT-LIB file I thought that maybe it is still possible.

- When I use read_smtlib to read a file that contains the line "(set-logic BV)" I get the warning "UserWarning: Unknown logic 'BV'. Ignoring set-logic command." I am wondering why I get this warning. This is a valid SMT-LIB logic (it can even be found in the SMT-LIB benchmarks) and pysmt supports quantified bit vectors. Do I somehow use pysmt incorrectly?. The subsequent SMT-LIB code causes this behaviour.
```
(set-logic BV)
(assert (forall ((x (_ BitVec 3))) (= x (bvadd x #b000))))
(check-sat)
```

- When I read a SMT-LIB file containing a "bvadd" with more than two arguments the parser reports an error -- apparently the parser expects that a bvadd expressions has not more than two arguments. But according to the description of the SMT-LIB BitVector theory bvadd has the "left-assoc" attribute. Thus, bvadd may have more than two arguments. The subsequent SMT-LIB code causes this behaviour.
```
(set-logic QF_BV)
(assert (= (bvadd #b01 #b01 #b01) #b11))
(check-sat)
```

By the way I am using pysmt 0.9.0.

thanks!

**Comment by mikand** [comment] 2021-04-29 09:16
Hi @lycurgus8,
thanks for using pysmt! I try to answer you by points, let me know if something is not clear.

- Z3 4.8.1 removed the interpolation API upstream, so interpolation with Z3 is no longer available via pysmt.
- Since pysmt is a python library, there is no need for let expressions, you can create and re-use python variables and functions:
```python
a = Plus(Symbol('x', INT), Int(3)) # let a = x + 3
def f(x):
    Plus(x, x)  # equivalent to a define-fun f with param x as x + x 
phi = f(a)
```
- Pysmt does not support the `BV` theory (it only supports `QF_BV`), hence the warning. This is mostly a pysmt trivial limitation in the encoding towards solvers that support `BV`, but the support is not there yet.
- This is a bug, for some reason pysmt currently only supports binary BVAdd: https://github.com/pysmt/pysmt/blob/master/pysmt/formula.py#L733

**Comment by lycurgus8** [comment] 2021-04-29 09:58
Hi @mikand 
thanks a lot for your quick response!

- Could you maybe update the table concerning the solver support in the readme -- according to this table pysmt still supports interpolation with z3.
- Sorry, thanks for pointing that out.
- I thought that pysmt supports the theory BV -- according to the already mentioned table the theory BV is supported (e.g. with z3).

**Comment by marcogario** [comment] 2022-07-08 08:21
To be clear:
* The **theory** BV is supported. 
* The logic `BV` is also [defined](https://github.com/pysmt/pysmt/blob/5567d3cb3a0b8527e635ab1926d9ca264dbe0183/pysmt/logics.py#L443) in pySMT. 
* What logics are defined in SMT-LIB is a bit tricky to answer. According to the [website](https://smtlib.cs.uiowa.edu/logics.shtml) there is no `BV` logic . This gives raise to this (ugly) distinction we keep in [logics.py](https://github.com/pysmt/pysmt/blob/5567d3cb3a0b8527e635ab1926d9ca264dbe0183/pysmt/logics.py#L628) between `SMTLIB2_LOGICS` and `PYSMT_LOGICS`.
* Solvers like Z3 and CVC4 are defined as supporting a larger set than SMT-LIB (by setting the `LOGICS` variable to a subset of `PYSMT_LOGICS` see [z3.py](https://github.com/pysmt/pysmt/blob/5567d3cb3a0b8527e635ab1926d9ca264dbe0183/pysmt/solvers/z3.py#L140)), so you should be able to solve problems in the `BV` logic.


AFAIU the actions here are:
- [ ] Update documentation/examples to clarify that pySMT does not support interpolants via Z3 anymore
- [ ] Try to reproduce the issue of the BVAdd associativity, as this might have been solved by the work done for the SMTCOMP. Fixing it should be fairly straightforward otherwise.

**Comment by marcogario** [comment] 2022-07-08 08:37
https://github.com/pysmt/pysmt/pull/727 updates the README. I could not find any other example talking about Z3 and interpolation outside of the README.

The bvadd associativity has been fixed in https://github.com/pysmt/pysmt/pull/714
To reproduce:
```
from io import StringIO
from pysmt.smtlib.parser import get_formula

FILE="""
(set-logic QF_BV)
(assert (= (bvadd #b01 #b01 #b01) #b11))
(check-sat)
"""

f = get_formula(StringIO(FILE))
print(f)
```

Thanks for reporting these problems ❤ . Feel free to re-open the issue if you think there is more work to be done here.

**Closed by marcogario** 2022-07-08 08:37 UTC
