### ISSUE TITLE
Floating Point Theory 

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#285] opened 2016-07-24 20:04 UTC
Floating point is now the only theory from the SMT-LIB that we do not support.

Mathsat supports it, we can use its API to decide which operators to support.

**Comment by marcogario** [comment] 2016-10-25 12:24
http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml

**Comment by shaobo-he** [comment] 2018-11-28 23:04
Hello, @marcogario May I ask when floating-point theory will be supported? Anytime soon?

**Comment by shaobo-he** [comment] 2018-11-29 03:45
I'd love to but my Python programming skill only allows me to write trivial programs. I'll let you know if I will do it.

**Comment by shaobo-he** [comment] 2020-04-05 22:17
Hey @marcogario. Since I got more familiarized with pysmt through one of my recent projects, I'm willing to take the task of adding floating-point support. Please let me know if you or others are already working on it in order to avoid duplicating work.

**Comment by mikand** [comment] 2020-04-06 08:27
I can confirm nobody is currently working on this, and any contribution is very welcome!
Let us know if you need any support or help

**Comment by shaobo-he** [comment] 2020-04-06 21:54
Sounds good. I'll submit a PR once I get something working.

**Comment by miriameisenhofer** [comment] 2022-02-22 20:30
Hello @shaobo-he , if floating-point support is still being worked on, do you have a rough time estimate for when it will be available?

**Comment by shaobo-he** [comment] 2022-02-23 01:48
> Hello @shaobo-he , if floating-point support is still being worked on, do you have a rough time estimate for when it will be available?

Hello, I'm no longer working on floating point support. Please feel free to close this issue.

**Closed** 2022-05-24 10:04 UTC
