### ISSUE TITLE
Mathsat installation on MacOS

### ISSUE THREAD

**Issue by cristian-mattarei** [pysmt/pysmt#519] opened 2018-08-16 21:55 UTC
``pysmt-install --msat`` does not work on MacOS (with the pip package). It does work on the master branch if you clone and install pysmt directly from https://github.com/pysmt/pysmt

**Comment by marcogario** [comment] 2018-08-19 12:46
What is the error?

**Comment by marcogario** [comment] 2018-08-19 12:52
Is this related to #518 ?

**Comment by marcogario** [comment] 2018-10-13 16:35
Closing since we cannot reproduce.

**Closed by marcogario** 2018-10-13 16:35 UTC
