### ISSUE TITLE
z3.num import error when z3 is installed through pysmt

### ISSUE THREAD

**Issue by smover** [pysmt/pysmt#603] opened 2019-08-27 10:21 UTC
Pysmt ends with the following exception trying to get back an algebraic number from z3:
```
Traceback (most recent call last):
  File "./reproduce.py", line 15, in <module>
    print(solver.get_model())
  File "/usr/local/lib/python2.7/site-packages/pysmt/solvers/solver.py", line 496, in __str__
    return "\n".join([ "%s := %s" % (var, value) for (var, value) in self])
  File "/usr/local/lib/python2.7/site-packages/pysmt/solvers/z3.py", line 98, in __iter__
    yield pysmt_d, self.get_value(pysmt_d)
  File "/usr/local/lib/python2.7/site-packages/pysmt/solvers/z3.py", line 84, in get_value
    return self.converter.back(z3_res, model=self.z3_model)
  File "/usr/local/lib/python2.7/site-packages/pysmt/solvers/z3.py", line 479, in back
    res = self._back_single_term(current, args, model)
  File "/usr/local/lib/python2.7/site-packages/pysmt/solvers/z3.py", line 543, in _back_single_term
    return self.mgr._Algebraic(Numeral(expr))
  File "/usr/local/lib/python2.7/site-packages/pysmt/constants.py", line 201, in __init__
    raise NotImplementedError("Z3 is not installed. "\
NotImplementedError: Z3 is not installed. We currently do not support stand-alone algebraic numbers.
```

I installed z3 through the pysmt install scripts (e.g., ```pysmt-install --z3```) and the z3  installation is in:
```
>>> print z3
print z3
<module 'z3' from '~/.smt_solvers/python-bindings-2.7/z3.pyc'>
```

In the `constants.py` file the import for the z3 numbers is `import z3.z3num`. However, I have the `z3num.py` module directly in `~/.smt_solvers/python-bindings-2.7`, which was installed automatically.

To reproduce the error you can use the following code:
```python
from pysmt.shortcuts import Solver, Equals, Real, Symbol
from pysmt.logics import QF_NRA
from pysmt.typing import REAL

from fractions import Fraction

solver = Solver(logic=QF_NRA, name="z3")

x = Symbol("x", REAL)
formula = Equals(x*x, Real(Fraction(2,1)))
solver.is_sat(formula)
print(solver.get_model())
```
Also, you have to check to not have another version of z3 installed on your system (that can provide you a z3num.py module in the right location).

As additional information, this is the configuration of my installation (output of `pymst-install --check`):
``` $> pysmt-install --check 
WARNING: unknown parameter 'model_compress'
Legal parameters are:
  auto_config (bool) (default: true)
  debug_ref_count (bool) (default: false)
  dump_models (bool) (default: false)
  memory_high_watermark (unsigned int) (default: 0)
  memory_max_alloc_count (unsigned int) (default: 0)
  memory_max_size (unsigned int) (default: 0)
  model (bool) (default: true)
  model_validate (bool) (default: false)
  proof (bool) (default: false)
  rlimit (unsigned int) (default: 4294967295)
  smtlib2_compliant (bool) (default: false)
  timeout (unsigned int) (default: 4294967295)
  trace (bool) (default: false)
  trace_file_name (string) (default: z3.log)
  type_check (bool) (default: true)
  unsat_core (bool) (default: false)
  verbose (unsigned int) (default: 0)
  warning (bool) (default: true)
  well_sorted_check (bool) (default: false)

Installed Solvers:
  msat      True (5.3.13)            
  cvc4      False (None)              Not in Python's path!
  z3        True (4.4.1)             
  yices     False (None)              Not in Python's path!
  btor      False (None)              Not in Python's path!
  picosat   False (None)              Not in Python's path!
  bdd       False (None)              Not in Python's path!
```

**Comment by marcogario** [comment] 2019-10-07 20:17
The fact that you get a bunch of information from z3 during the `--check` is suspicious.
What OS are you using?

Upgrade to python 3, python 2.7 will reach end-of-life at the end of the year.

**Comment by marcogario** [comment] 2020-04-12 09:38
@smover can you see if this reproduces on master? Otherwise, please close the issue.

**Comment by marcogario** [comment] 2022-05-28 14:41
Cannot reproduce with pySMT 0.9.5, z3 4.8.7 and python 3.9. The example works as expected, although I get a segfault after running it. The segfault is more related to general issues we have with the z3 wrapper, but that is not what this issue is about.

**Closed by marcogario** 2022-05-28 14:41 UTC
Labels: bug
